# Generated by Django 4.2.6 on 2024-01-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='uploads/products/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'shop"."products',
                'ordering': ['name'],
            },
        ),
    ]
